[owl]
version = "1.0.0"

[project]
name = "kioto"
version = "0.2.0"
entry = "code/main.mire"
description = "Kioto standard library project"

[dependencies]

[build]
default_profile = "debug"
default_opt_level = "0"
